# Warning! Autogenerated file by cumulus
# Do NOT edit it directly, all changes may be removed

''
:root {
  --toolbar-bgcolor: #161616 !important;
  --tab-selected-bgcolor: #525252 !important;
}

#navigator-toolbox {
  background-color: #161616 !important;
}

#urlbar-background {
  background-color: #525252 !important;
}

#TabsToolbar {
  --lwt-tab-line-color: #00000000 !important;
}

#nav-bar {
  border-top: none !important;
}

#navigator-toolbox {
  border-bottom: none !important;
}

.titlebar-buttonbox-container {
  display: none !important;
}

#tabbrowser-tabs {
  border-inline-start: none !important;
}

.titlebar-spacer {
  width: 0 !important;
}
''